{
 "title": "Global Production",
 "description": "Satisfactory statistics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(url)" } },
   {
    "name": "session",
    "query": {
     "query": "label_values({url=\"$server\"},session_name)"
    }
   },
   {
    "name": "item",
    "query": {
     "query": "label_values(item_production_capacity_per_min,item_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Production Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  { "title": "Global Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Current Production",
   "type": "table",
   "description": "Global production",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(prod.name, cons.name) as name,\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) as rate\nfrom\n  (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.ingredients[*]') ->> 'Name' as name,\n          (\n            (jsonb_path_query(data, '$.ingredients[*]') ->> 'CurrentConsumed') :: NUMERIC\n          ) as val\n        FROM\n          cache\n         \n        where\n          metric in ('factory', 'extractor')\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n    order by\n      t.name\n  ) as cons full\n  outer join (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.production[*]') ->> 'Name' as name,\n          (jsonb_path_query(data, '$.production[*]') ->> 'CurrentProd') :: NUMERIC as val\n        FROM\n          cache\n         \n        where\n          metric in ('factory', 'extractor')\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n    order by\n      t.name\n  ) as prod on cons.name = prod.name\nwhere\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) != 0\norder by\n  rate desc,\n  name"
    }
   ]
  },
  {
   "title": "Max Production",
   "type": "table",
   "description": "Max global production",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n  COALESCE(prod.name, cons.name) as name,\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) as rate\nfrom\n  (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.ingredients[*]') ->> 'Name' as name,\n          (\n            (jsonb_path_query(data, '$.ingredients[*]') ->> 'MaxConsumed') :: NUMERIC\n          ) val\n        FROM\n          cache\n         \n        where\n          metric in('factory', 'extractor')\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n    order by\n      t.name\n  ) as cons full\n  outer join (\n    SELECT\n      t.name,\n      sum(t.val) as rate\n    from\n      (\n        SELECT\n          jsonb_path_query(data, '$.production[*]') ->> 'Name' as name,\n          (jsonb_path_query(data, '$.production[*]') ->> 'MaxProd') :: NUMERIC val\n        FROM\n          cache\n         \n        where\n          metric in ('factory', 'extractor')\n          and url = '$server'\n          and session_name = '$session'\n      ) as t\n    group by\n      t.name\n    order by\n      t.name\n  ) as prod on cons.name = prod.name\nwhere\n  COALESCE(prod.rate, 0) - COALESCE(cons.rate, 0) != 0\norder by\n  rate desc,\n  name"
    }
   ]
  },
  { "title": "$item Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Production vs consumption /min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "item_production_capacity_per_min{item_name=\"$item\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "items_produced_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "item_consumption_capacity_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "items_consumed_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Production vs consumption %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "item_production_capacity_pc{item_name=\"$item\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "item_consumption_capacity_pc{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Resource Sink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Sink Points",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "resource_sink_total_points{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{sink_type}}"
    }
   ]
  },
  {
   "title": "Points to coupon",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "resource_sink_points_to_coupon", "legendFormat": "{{sink_type}}" }
   ]
  },
  {
   "title": "Available Tickets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resource_sink_collected_coupons{url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}