{
 "title": "Power",
 "description": "Satisfactory statistics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "circuit",
    "query": {
     "query": "{circuit_id=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Power Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  { "title": "Circuit $circuit Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Fuse",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_triggered{circuit_id=\"$circuit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_percent{circuit_id=\"$circuit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery minutes remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_seconds_empty{circuit_id=\"$circuit\"} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "power_capacity{circuit_id=\"$circuit\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_max_consumed{circuit_id=\"$circuit\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_consumed{circuit_id=\"$circuit\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Battery charge rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "battery_differential{circuit_id=\"$circuit\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Circuit $circuit map",
   "type": "geomap",
   "description": "Map of where circuit $circuit is operating",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'building' as building,\ndata ->> 'CircuitID' as circuit,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 374950) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nFROM cache\ncross join jsonb_path_query(frm_data, '$[*]') as data\nwhere metric = 'factory'\nand (data ->> 'CircuitID')::numeric = $circuit\nLIMIT 500"
    }
   ]
  }
 ]
}