{
 "title": "Satisfactory",
 "description": "Satisfactory statistics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "circuit",
    "query": {
     "query": "{circuit_id=~\".+\"}"
    }
   },
   {
    "name": "item",
    "query": {
     "query": "{item_name=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Power Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  { "title": "Production Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 } },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Battery minutes remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_seconds_empty{circuit_id=\"$circuit\"} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_percent{circuit_id=\"$circuit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fuse",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_triggered{circuit_id=\"$circuit\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "power_capacity{circuit_id=\"$circuit\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_max_consumed{circuit_id=\"$circuit\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_consumed{circuit_id=\"$circuit\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Battery charge rate rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "battery_differential{circuit_id=\"$circuit\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  { "title": "Production", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Production vs consumption /min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "item_production_capacity_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "items_produced_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "item_consumption_capacity_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "items_consumed_per_min{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Production vs consumption %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "item_production_capacity_pc{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "item_consumption_capacity_pc{item_name=\"$item\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}