{
 "title": "Power (Template)",
 "description": "Satisfactory statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "server", "query": { "query": "label_values(url)" } },
   {
    "name": "session",
    "query": {
     "query": "label_values({url=\"$server\"},session_name)"
    }
   },
   {
    "name": "circuit",
    "query": {
     "query": "{circuit_id=~\".+\",url=~\"$server\",session_name=~\"$session\"}"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Power Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 } },
  { "title": "Circuit $circuit Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Fuse",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "fuse_triggered{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery charge",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_percent{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery minutes remaining",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "battery_seconds_empty{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"} / 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery charge rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "mwatth" } },
   "targets": [
    {
     "expr": "battery_differential{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "power_capacity{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_max_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "power_consumed_overhead_or_max_consumed:min6h{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "real_power_consumed_max"
    }
   ]
  },
  {
   "title": "Power Breakdown",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(vehicle_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Truck Stations"
    },
    {
     "expr": "sum(last_over_time(train_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Train Stations"
    },
    {
     "expr": "sum(last_over_time(train_power_circuit_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Trains"
    },
    {
     "expr": "sum(last_over_time(drone_port_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Drone Ports"
    },
    {
     "expr": "sum(last_over_time(factory_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Factory"
    },
    {
     "expr": "sum(last_over_time(resource_sink_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Sinks"
    },
    {
     "expr": "sum(last_over_time(pump_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Pumps"
    },
    {
     "expr": "sum(last_over_time(extractor_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Extractors"
    },
    {
     "expr": "sum(last_over_time(portal_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Portals"
    },
    {
     "expr": "sum(last_over_time(hypertube_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Hypertubes"
    },
    {
     "expr": "sum(last_over_time(fracking_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}[$__range]) or vector(0))",
     "legendFormat": "Resource Well Pressurizers"
    },
    {
     "expression": "$TOTAL-$DRONE-$TRAIN-$TRAIN_STATION-$VEHICLE_STATION-$FACTORY-$SINK-$PUMPS-$EXTRACTORS-$PORTALS-$HYPERTUBES-$RESOURCE_WELLS",
     "type": "math"
    }
   ]
  },
  {
   "title": "Circuit $circuit map",
   "type": "geomap",
   "description": "Map of where circuit $circuit is operating",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\ndata ->> 'Name' as building,\ndata ->'PowerInfo' ->> 'CircuitGroupID' as circuit,\ndata ->> 'Recipe' as recipe,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache where metric in ('factory', 'extractor')\nand (data -> 'PowerInfo' ->> 'CircuitGroupID')::numeric = $circuit\nand url = '$server'\nand session_name = '$session'"
    }
   ]
  },
  {
   "title": "Circuit and building counts",
   "type": "table",
   "description": "number of buildings on each circuit",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "select \ndata -> 'PowerInfo' ->> 'CircuitGroupID' as circuit,\ncount(*) as building_count\nfrom cache where metric in ('factory', 'extractor')\nand url = '$server'\nand session_name = '$session'\ngroup by circuit\norder by building_count"
    }
   ]
  },
  {
   "title": "Circuit $circuit Power Breakdown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 }
  },
  {
   "title": "Factory Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "factory_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "factory_power_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Vehicle Station Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "vehicle_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "vehicle_station_power_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Train Station Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "train_station_power{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "train_station_power_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Train Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "megwatt" } },
   "targets": [
    {
     "expr": "train_power_circuit_consumed{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    },
    {
     "expr": "train_power_circuit_consumed_max{circuit_id=\"$circuit\", url=\"$server\", session_name=\"$session\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}