{
 "title": "Vehicles",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "vehicle",
    "label": "Vehicle",
    "query": "select\ndata->>'ID'\nfrom cache cross join jsonb_path_query(frm_data, '$[*]') as data where metric = 'truck'\norder by id desc;"
   }
  ]
 },
 "panels": [
  {
   "title": "Truck Routes",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\ndata,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation') as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache_with_history cross join jsonb_path_query(frm_data, '$[*]') as data where metric = 'truck'\nand data ->> 'ID' = '$vehicle'\norder by time desc\nlimit 100;\n"
    },
    {
     "rawSql": "select\nconcat(data->>'ID',':',data->>'VehicleType') as vehicle,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache cross join jsonb_path_query(frm_data, '$[*]') as data where metric = 'truck'\nand data ->> 'ID' = '$vehicle';\n"
    },
    {
     "rawSql": "select\ndata,\n(data -> 'location' ->> 'x')::NUMERIC/100 as x,\n(data -> 'location' ->> 'y')::NUMERIC/100 as y,\n(data -> 'location' ->> 'z')::NUMERIC/100 as z,\n(data -> 'location' ->> 'rotation')::NUMERIC as rotation,\n(((data -> 'location' ->> 'x')::NUMERIC + 375000) * 0.0000001015) as longitude,\n(((data -> 'location' ->> 'y')::NUMERIC + 375000) * -0.0000001172) as latitude\nfrom cache cross join jsonb_path_query(frm_data, '$[*]') as data where metric = 'truckStation'\nlimit 100;\n"
    }
   ]
  },
  {
   "title": "Vehicle list",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\ndata->>'ID' as id,\ndata->>'VehicleType' as type,\ndata->>'PathName' as path_name\nfrom (\n  SELECT frm_data from cache_with_history WHERE metric = 'truck' ORDER BY id desc limit 1\n) as t\n cross join jsonb_path_query(t.frm_data, '$[*]') as data limit 100;"
    }
   ]
  },
  { "title": "Vehicles", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Fuel Loadout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "vehicle_fuel{vehicle_type!=\"Factory Cart\"}",
     "legendFormat": "{{id}} ({{vehicle_type}}) - {{fuel_type}}"
    }
   ]
  },
  {
   "title": "Vehicle Round trip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "vehicle_round_trip_seconds / 60",
     "legendFormat": "{{id}} ({{vehicle_type}}) - {{path_name}}"
    }
   ]
  }
 ]
}